### ISSUE TITLE
No module named weakref

### ISSUE THREAD

**Issue by kiwizznz** [3tc/efergy2mqtt#1]
I think I've followed the guide (thank you by the way! really great to see someone else has already done what I'm trying to do) but am stuck at pipenv install, with the following error: 'ImportError: No module named weakref' details:

pi@AMRIDM2MQTT:~/sdr/efergy2mqtt $ pipenv install
Traceback (most recent call last):
  File "/home/pi/.local/bin/pipenv", line 6, in <module>
    from pipenv import cli
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
    from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
    from .tempfile import NamedTemporaryFile
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
    from backports.weakref import finalize
ImportError: No module named weakref
pi@AMRIDM2MQTT:~/sdr/efergy2mqtt $ ./run.sh
pi@AMRIDM2MQTT:~/sdr/efergy2mqtt $ Traceback (most recent call last):
  File "/home/pi/.local/bin/pipenv", line 6, in <module>
    from pipenv import cli
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
    from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
    from .tempfile import NamedTemporaryFile
  File "/home/pi/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
    from backports.weakref import finalize
ImportError: No module named weakref

Did a google for the error and one suggestion was this: 
pi@AMRIDM2MQTT:~/sdr/efergy2mqtt $ pip install backports.weakref
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting backports.weakref
  Downloading https://files.pythonhosted.org/packages/88/ec/f598b633c3d5ffe267aaada57d961c94fdfa183c5c3ebda2b6d151943db6/backports.weakref-1.0.post1-py2.py3-none-any.whl
Installing collected packages: backports.weakref
Successfully installed backports.weakref-1.0.post1

Which also didn't help. Any suggestions on what to try next? Might be helpful but is a bit of a mess, the command history: 

  44  cd efergy2mqtt/
   45  ls
   46  python3 -m pip --user pipenv
   47  pipenv install
   48  pipenv shell
   49  cd ..
   50  ls
   51  cd RPI_Efergy/
   52  pipenv install
   53  cd ..
   54  cd efergy2mqtt/
   55  ls
   56  echo .env
   57  echo $.env
   58  cat .env
   59  ls
   60  echo 'EFERGY_BINARY=/home/pi/sdr/RPI_Efergy/EfergyRPI_log' >> .env
   61  echo 'MQTT_HOST=xxx' >> .env
   62  echo 'MQTT_USER=xxx' >> .env
   63  echo 'MQTT_PASS=xxx' >> .env
   64  cat .env
   65  python3 -m pip --user pipenv
   66  pipenv install
   67  pip install --user pipx
   68  pip --version
   69  sudo apt-get install pip
   70  python -m ensurepip --upgrade
   71  sudo apt-get install python-pip
   72  curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
   73  pip install --user pipenv
   74  pipenv shell
   75  ./run.sh
   76  pipenv install
   77  python3 -m pip --user pipenv
   78  pip install paho.mqtt
   79  cat run.sh
   80  pipenv
   81  pip install --user pipenv
   82  python -m site --user-base
   83  ls
   84  ls -la
   85  python -m site --user-base
   86  export PATH=$PATH:/home/pi/.local/bin
   87  pipenv install
   88  ./run.sh
   89  pip install backports.weakref
   90  pipenv install
   91  ./run.sh
   92  pi@AMRIDM2MQTT:~/sdr/efergy2mqtt $ ./run.sh
   93  pi@AMRIDM2MQTT:~/sdr/efergy2mqtt $ Traceback (most recent call last):
   94  ImportError: No module named weakref
   95  history

**Comment by 3tc** [comment]
Appologies for the late reply. Looking at the output you posted "File "/home/pi/.local/lib/python2.7/", it could be that your path is pointing to python2, not python3.  Also when using pip use pip3 or python3 -m pip.

**Comment by kiwizznz** [comment]
All good, thanks for the reply! Ended up doing a whole rebuild and banged my head for a few more hours. Eventually got it working but can't remember what I did specifically :)
